

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: navin
      MYSQL_DATABASE: employee_management
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:6.0
    container_name: mongo-container
    restart: always
    ports:
      - "27018:27017"   # changed host port to avoid conflict
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: navaneethakrishna/backend-app:latest
    container_name: backend-container
    restart: always
    ports:
      - "5001:8080"     # changed host port to avoid conflict
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_management
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: navin
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/employee_management
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  frontend:
    image: navaneethakrishna/frontend-app:latest
    container_name: frontend-container
    restart: always
    ports:
      - "3001:80"       # changed host port to avoid conflict
    depends_on:
      - backend

volumes:
  mysql_data:
  mongo_data:
